# Generated by Django 2.2.13 on 2020-07-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('Course', models.CharField(max_length=100)),
                ('Teacher', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('ClassNumber', models.IntegerField()),
                ('EnrollmentCapacity', models.IntegerField()),
                ('Final', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('University', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('Major', models.CharField(max_length=50)),
                ('EntryYear', models.CharField(max_length=50)),
                ('DateOfBirth', models.CharField(max_length=50)),
                ('SSN', models.BinaryField()),
                ('FatherName', models.CharField(max_length=50)),
                ('CellularPhoneNumber', models.CharField(max_length=50)),
                ('FatherCellularPhoneNumber', models.CharField(max_length=50)),
                ('MotherCellularPhoneNumber', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('DebitCardNumber', models.BinaryField()),
                ('Username', models.BinaryField()),
                ('Password', models.BinaryField()),
                ('PassedCourses', models.CharField(max_length=10000)),
                ('CurrentCourses', models.CharField(max_length=10000)),
                ('UndergraduateCourses', models.CharField(max_length=10000)),
                ('Study', models.CharField(max_length=50)),
                ('Image', models.CharField(max_length=1000)),
                ('Email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
    ]
