# Generated by Django 2.2.13 on 2020-07-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200720_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester1', models.CharField(max_length=20000)),
                ('semester2', models.CharField(max_length=20000)),
                ('semester3', models.CharField(max_length=20000)),
                ('semester4', models.CharField(max_length=20000)),
                ('semester5', models.CharField(max_length=20000)),
                ('semester6', models.CharField(max_length=20000)),
                ('semester7', models.CharField(max_length=20000)),
                ('semester8', models.CharField(max_length=20000)),
            ],
            options={
                'db_table': 'Semester',
            },
        ),
    ]
